/** Renders static product documentation without coupling it to study state. */
export function renderDocsView() {
  return `<article class="docs-layout">
  <aside class="docs-toc"><span class="eyebrow">DOCUMENTATION</span><h1>使用文档</h1><nav><a href="#quick-start">开始使用</a><a href="#ratings">复习反馈</a><a href="#memory">记忆调度</a><a href="#queue">每日队列</a><a href="#data">数据与导出</a><a href="#architecture">工作流</a></nav></aside>
  <div class="docs-content">
    <section id="quick-start"><span class="section-index">01</span><h2>开始使用</h2><p>公共页面将进度保存在当前浏览器。本地模式通过 <code>npm run local</code> 启动，并自动写入 <code>profiles/default.json</code>。</p><div class="docs-callout"><b>推荐流程</b><span>看词 → 主动回忆 → Space 查看答案 → WASD 评分。误触时按 Z 撤销并返回。</span></div></section>
    <section id="ratings"><span class="section-index">02</span><h2>四级复习反馈</h2><div class="rating-grid"><div><kbd>A</kbd><b>完全忘记</b><p>无法回忆或回答错误。约 30 分钟后再次出现。</p></div><div><kbd>S</kbd><b>回忆困难</b><p>最终想起，但耗时或犹豫明显。安排较短间隔。</p></div><div><kbd>D</kbd><b>正常掌握</b><p>在合理时间内正确回忆。逐步延长复习间隔。</p></div><div class="master-doc"><kbd>W</kbd><b>完全掌握</b><p>移出自动复习队列。请谨慎选择，可从历史记录恢复。</p></div></div></section>
    <section id="memory"><span class="section-index">03</span><h2>记忆如何变化</h2><p>每次成功回忆会提高记忆强度，并延长下一次复习间隔。困难反馈缩短间隔，遗忘反馈重置学习阶段。</p><svg class="memory-svg" viewBox="0 0 760 240" role="img" aria-label="三次复习逐渐延长记忆间隔"><line x1="42" y1="202" x2="730" y2="202"/><line x1="42" y1="24" x2="42" y2="202"/><path d="M42 42 C82 58 112 126 145 184 M145 42 C205 58 258 120 306 184 M306 42 C408 55 520 122 616 184 M616 42 C658 50 700 76 730 108"/><g><circle cx="145" cy="184" r="5"/><circle cx="306" cy="184" r="5"/><circle cx="616" cy="184" r="5"/></g><g class="labels"><text x="117" y="222">复习 1</text><text x="278" y="222">复习 2</text><text x="588" y="222">复习 3</text><text x="50" y="34">记忆强度</text></g></svg></section>
    <section id="queue"><span class="section-index">04</span><h2>每日学习队列</h2><p>词库按词频分成五层，每层每天确定性抽取四个未学词。到期复习词与新词交错出现，同一天刷新不会更换词组，也不会突破 20 个新词的配额。</p><div class="strata"><span>高频 × 4</span><span>较高频 × 4</span><span>中频 × 4</span><span>较低频 × 4</span><span>低频 × 4</span></div></section>
    <section id="data"><span class="section-index">05</span><h2>数据与可选接口</h2><ul><li>JSON：完整备份学习记录，可在另一台电脑导入。</li><li>Anki TSV：默认关闭，只导出至少学习过一次的词。</li><li>拼写练习：默认关闭，仅在“完全忘记”后触发，不影响评分。</li></ul></section>
    <section id="architecture"><span class="section-index">06</span><h2>发布工作流</h2><div class="pipeline"><span>Push</span><i>→</i><span>Tests</span><i>→</i><span>Build</span><i>→</i><span>Pages</span></div><p>每次发布都会运行单元测试、类型检查和生产构建。只有完整构建产物会部署到公共 Demo。</p></section>
  </div></article>`;
}
